/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as ShemaghsRouteImport } from './routes/shemaghs'
import { Route as NiqabsRouteImport } from './routes/niqabs'
import { Route as HoneyRouteImport } from './routes/honey'
import { Route as GlovesRouteImport } from './routes/gloves'
import { Route as IndexRouteImport } from './routes/index'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ShemaghsRoute = ShemaghsRouteImport.update({
  id: '/shemaghs',
  path: '/shemaghs',
  getParentRoute: () => rootRouteImport,
} as any)
const NiqabsRoute = NiqabsRouteImport.update({
  id: '/niqabs',
  path: '/niqabs',
  getParentRoute: () => rootRouteImport,
} as any)
const HoneyRoute = HoneyRouteImport.update({
  id: '/honey',
  path: '/honey',
  getParentRoute: () => rootRouteImport,
} as any)
const GlovesRoute = GlovesRouteImport.update({
  id: '/gloves',
  path: '/gloves',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gloves': typeof GlovesRoute
  '/honey': typeof HoneyRoute
  '/niqabs': typeof NiqabsRoute
  '/shemaghs': typeof ShemaghsRoute
  '/v2': typeof V2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gloves': typeof GlovesRoute
  '/honey': typeof HoneyRoute
  '/niqabs': typeof NiqabsRoute
  '/shemaghs': typeof ShemaghsRoute
  '/v2': typeof V2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gloves': typeof GlovesRoute
  '/honey': typeof HoneyRoute
  '/niqabs': typeof NiqabsRoute
  '/shemaghs': typeof ShemaghsRoute
  '/v2': typeof V2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gloves' | '/honey' | '/niqabs' | '/shemaghs' | '/v2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gloves' | '/honey' | '/niqabs' | '/shemaghs' | '/v2'
  id: '__root__' | '/' | '/gloves' | '/honey' | '/niqabs' | '/shemaghs' | '/v2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlovesRoute: typeof GlovesRoute
  HoneyRoute: typeof HoneyRoute
  NiqabsRoute: typeof NiqabsRoute
  ShemaghsRoute: typeof ShemaghsRoute
  V2Route: typeof V2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shemaghs': {
      id: '/shemaghs'
      path: '/shemaghs'
      fullPath: '/shemaghs'
      preLoaderRoute: typeof ShemaghsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niqabs': {
      id: '/niqabs'
      path: '/niqabs'
      fullPath: '/niqabs'
      preLoaderRoute: typeof NiqabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honey': {
      id: '/honey'
      path: '/honey'
      fullPath: '/honey'
      preLoaderRoute: typeof HoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gloves': {
      id: '/gloves'
      path: '/gloves'
      fullPath: '/gloves'
      preLoaderRoute: typeof GlovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlovesRoute: GlovesRoute,
  HoneyRoute: HoneyRoute,
  NiqabsRoute: NiqabsRoute,
  ShemaghsRoute: ShemaghsRoute,
  V2Route: V2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
